from __future__ import annotations

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.orm import declarative_base, sessionmaker

from app.config import settings

def normalize_database_url(url: str) -> str:
    if url.startswith("postgres://"):
        return url.replace("postgres://", "postgresql+psycopg://", 1)
    if url.startswith("postgresql://") and "+psycopg" not in url:
        return url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url

DATABASE_URL = normalize_database_url(settings.database_url)

connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(
    DATABASE_URL,
    future=True,
    pool_pre_ping=True,
    connect_args=connect_args,
)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)
Base = declarative_base()

def ensure_runtime_schema() -> None:
    inspector = inspect(engine)
    existing_tables = set(inspector.get_table_names())

    with engine.begin() as conn:
        if "region_market_snapshots" in existing_tables:
            columns = {col["name"] for col in inspector.get_columns("region_market_snapshots")}
            if "best_sell_location_id" not in columns:
                conn.execute(text("ALTER TABLE region_market_snapshots ADD COLUMN best_sell_location_id BIGINT"))
            if "best_buy_location_id" not in columns:
                conn.execute(text("ALTER TABLE region_market_snapshots ADD COLUMN best_buy_location_id BIGINT"))

        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS user_roles (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                role VARCHAR(50) NOT NULL DEFAULT 'user',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        """))
        conn.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS uq_user_roles_user_id ON user_roles (user_id)"))
        conn.execute(text("CREATE INDEX IF NOT EXISTS ix_user_roles_role ON user_roles (role)"))

        conn.execute(text("""
            INSERT INTO user_roles (user_id, role)
            SELECT u.id, CASE WHEN u.handle = 'Varaxian' THEN 'super_admin' ELSE 'user' END
            FROM users u
            WHERE NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id)
        """))

        conn.execute(text("""
            UPDATE user_roles ur
            SET role = 'super_admin', updated_at = NOW()
            FROM users u
            WHERE ur.user_id = u.id AND u.handle = 'Varaxian' AND ur.role <> 'super_admin'
        """))

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
